@startuml er

entity "ユーザー" as user {
  id 
  --
  name[varchar]
}

entity "セルフケア分類" as self_care_classification {
  id
  --
  name [varchar]
  order_number[smallint]
  kind[tinyint]
}

entity "セルフケア" as self_care {
  id
  self_care_classification_id[FK]
  user_id[FK]
  --
  log_date[datetime]
  reason[text]
  point[tinyint|1~10]
}

self_care_classification ----{ self_care
user ----o{self_care

@enduml
